#!/usr/bin/env bash
set -eu

# Install the labextension
python setup.py sdist bdist_wheel
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter labextension develop . --overwrite

# List extensions
jupyter labextension list
